name: geek
version: 1.0.0+1
publish_to: none
description: reading application
environment: 
  sdk: '>=3.1.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  dio: 5.4.0
  pretty_dio_logger: ^1.3.1
  get_storage: ^2.1.1
  flutter: 
    sdk: flutter
  google_fonts: ^6.1.0
  email_validator: ^2.1.17
  flutter_pw_validator: ^1.6.0
  lottie: ^2.7.0
  curved_navigation_bar: ^1.0.3
  flutter_rating_bar: ^4.0.1
  liquid_pull_to_refresh: ^3.0.1
  shimmer: ^3.0.0
  quickalert: ^1.1.0
  pretty_qr_code: ^3.3.0
  image_picker: ^1.0.8
  flutter_image_compress: ^2.2.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/splash/

flutter_launcher_icons:
  android: launcher_icon
  image_path: assets/images/logo_white.png
  ios: true
